name: test

on:
  push:
    branches:
      - main

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dagger/dagger-for-github@v3
        with:
          cmds: do check
